### ISSUE TITLE
Daten für Sunny Boy Smart Energy 3.6, 4.0, 6.0

### ISSUE THREAD

**Issue by myrmidondvb** [littleyoda/pysma#3]
Moin @All,

hiermit sollten auch die andern Sunny Boy Smart Energy funktionieren.

definitions_ennexos.py

138  -    # Sunny Boy Smart Energy 5.0
138 +    # Sunny Boy Smart Energy 3.6, 4.0, 5.0, 6.0

140 -     [19130],
140 +    [19128, 19129, 19130, 19085],

Gruß Myrmidon

**Comment by myrmidondvb** [comment]
Falsche Abteilung

**Comment by myrmidondvb** [comment]
const.py

   624 + 19128: "Sunny Boy Smart Energy 3.6",
   625 + 19129: "Sunny Boy Smart Energy 4.0",
   626    19130: "Sunny Boy Smart Energy 5.0",
   627  +19085: "Sunny Boy Smart Energy 6.0",

Gruß Myrmidon

**Comment by littleyoda** [comment]
Hi
konntest du die Geräte schon testen?

Da SMA dazu neigt, die verfügbare Sensoren in jeder Version ein wenig anzupassen, wollte ich warten, bis jemand die Geräte auch wirklich hat.

**Comment by myrmidondvb** [comment]
Ich habe hier testweise einen SBSE6.0,  die ID's sollten passen, habe es noch nicht hinbekommen die Pakete zu bauen das diese unter HA auch laufen genommen werden.
Bekomme immer

![SBSE](https://github.com/user-attachments/assets/87b7d2f6-7c7b-41a1-a6d9-c8dce7cf8dbd)

Gruß Myrmidon

**Comment by littleyoda** [comment]
Schickst du mir mal die Debug-Informationen?
Dann schaue ich mir an, welche Sensoren er liefert und füge die ID hinzu.

https://littleyoda.github.io/

**Comment by myrmidondvb** [comment]
Das werden genau die gleichen sein wie bei den anderen Geräten SBSEx.0, sind ja bis auf die Leistung die gleichen Geräte.

**Comment by littleyoda** [comment]
schicke es mir bitte trotzdem.
bei den Tripower X unterscheiden sie sich auch.
Der Tripower X 20 hat z.B. einen Temperatur weniger.

**Comment by littleyoda** [comment]
Eingebaut
