### ISSUE TITLE
Third DC power sensor not available

### ISSUE THREAD

**Issue by ulrich379** [littleyoda/pysma#6]
Not available third mmp tracker DC Power: sensor.sunny_tripower_x_20_pv_power_c
In earlier versions, all three DC power sensors were vailable.
Tripower X over ennexos.

**Comment by littleyoda** [comment]
I assume you are using home assistant.
Have to enabled the sensor in Home Assistant?

![grafik](https://github.com/user-attachments/assets/40496c11-46dc-4608-9adb-a8def187902b)


"Entities not shown"

**Comment by littleyoda** [comment]
I assume that the problem has been solved. Otherwise, please reopen it.
